### ISSUE TITLE
Give specific peer an initial balance

### ISSUE THREAD

**Issue by raphjaph** [fiatjaf/poncho#2]
Is there a way to give a specific peer an initial balance?

I tried `hc-override <peerid> <msatoshi>` but I got 
```bash
{
   "message": "java.lang.Exception: can't send to this channel since it is not errored or in overriding state."
}

```

`lcli pay <invoice from peer>` also didn't work but that could be because of #1:
```
{
   "code": 210,
   "message": "Destination 02ee4eec2c5de2e37d3c4cbf7e0bc5b53e69898a76ad11c84aecdd0eab792004b4 is not reachable directly and all routehints were unusable.",
   "attempts": [
      {
         "status": "failed",
         "failreason": "Destination 02ee4eec2c5de2e37d3c4cbf7e0bc5b53e69898a76ad11c84aecdd0eab792004b4 is not reachable directly and all routehints were unusable.",
         "partid": 0,
         "amount": "10000000msat"
      }
   ]
}
```

**Comment by fiatjaf** [comment]
Overriding is only for channels that get into an error state (i.e. they can't agree about something and require manual action to resolve).

Paying to and from the hosted channel directly from the host is not supported yet because it requires changing the default behavior of CLN, which we can do and will in the future, but for now it was too much of a hassle for too little gain.

**Comment by raphjaph** [comment]
Good to know, thanks!

**Comment by fiatjaf** [comment]
Yes, but it's basically the same complexity as modifying the actual 'pay' command. We“ll get to that.
